'use strict';
/*  afterlife.js — Six dark cinematic Afterlife-aesthetic scenes.
    VOID CATHEDRAL, SACRED GEOMETRY, NEURAL SWARM, DARK MONOLITH,
    LASER CATHEDRAL, AFTERLIFE RINGS.                                   */

(function () {
var H = NX.HEAD;

/* 1. VOID CATHEDRAL — dark cavernous space, distant glowing arches, fog */
NX.registerScene({n:'VOID CATHEDRAL',c:'#7c4dff',fs:H+[
'float sdArch(vec3 p,float w,float h,float d){',
'  float cyl=length(vec2(max(length(p.xz)-w,0.),p.y-h))-d;',
'  float leg1=sdBox(p-vec3(-w,h*.5,0.),vec3(d,h*.5+d,d));',
'  float leg2=sdBox(p-vec3( w,h*.5,0.),vec3(d,h*.5+d,d));',
'  return min(cyl,min(leg1,leg2));',
'}',
'float map(vec3 p){',
'  vec3 q=p;q.z=mod(q.z+5.,10.)-5.;q.x=abs(q.x);',
'  float arch=sdArch(q-vec3(2.8,0.,0.),.6,3.5,.12+BT*.04);',
'  float fl=p.y+.01;',
'  float fog=sdSph(p-vec3(0.,2.5,0.),8.+B*2.);',
'  return min(min(arch,fl),fog*.6);',
'}',
'vec3 calcN(vec3 p){vec2 e=vec2(.002,0);return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),map(p+e.yxy)-map(p-e.yxy),map(p+e.yyx)-map(p-e.yyx)));}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  vec3 ro=vec3(sin(T*.08+MX.x)*.5,1.3+MX.y*.4,-3.+sin(T*.05)*2.);',
'  vec3 ta=vec3(0.,1.8,ro.z+5.);',
'  mat3 ca=camMat(ro,ta,sin(T*.03)*.015);',
'  vec3 rd=ca*normalize(vec3(sc,1.6));',
'  float td=0.;vec3 col=vec3(.005,.003,.01);',
'  for(int i=0;i<72;i++){',
'    vec3 p=ro+rd*td;float d=map(p);',
'    if(d<.005){',
'      vec3 n=calcN(p);',
'      float ao=1.-float(i)/72.*.5;',
'      vec3 ldir=normalize(vec3(.3,.8,-.4));',
'      col=blinnPhong(n,-rd,ldir,pal(p.z*.04+T*.06)*.35,0.04)*ao;',
'      float fog=exp(-td*.08-B*.02);col*=fog;',
'      col+=pal(T*.05+.3)*.08*(1.+BT*.6+FL*.3);',
'      break;',
'    }',
'    if(td>40.)break;td+=d*.7;',
'    col+=pal(T*.06+td*.02)*.0012*(1.+BT*.8)*exp(-td*.05);',
'  }',
'  vec2 fUV=feedUV(1.015+B*.01,.002*SP,vec2(0.,.001));',
'  col=mix(texture2D(PV,fUV).rgb*.94,col,.28+B*.18);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.88)),1.);',
'}'
].join('\n')});

/* 2. SACRED GEOMETRY — rotating platonic solids, wireframe glow */
NX.registerScene({n:'SACRED GEOMETRY',c:'#e040fb',fs:H+[
'float sdIcosa(vec3 p,float s){',
'  float g=1.618;',
'  vec3 n1=normalize(vec3(1,g,0)),n2=normalize(vec3(0,1,g)),n3=normalize(vec3(g,0,1));',
'  p=abs(p);',
'  float d=dot(p,n1);d=max(d,dot(p,n2));d=max(d,dot(p,n3));',
'  return d-s;',
'}',
'float sdDodeca(vec3 p,float s){',
'  float g=1.618;',
'  vec3 n1=normalize(vec3(0,1./g,g)),n2=normalize(vec3(1./g,g,0)),n3=normalize(vec3(g,0,1./g));',
'  p=abs(p);',
'  return max(max(dot(p,n1),dot(p,n2)),max(dot(p,n3),max(p.x,max(p.y,p.z))))-s;',
'}',
'float map(vec3 p){',
'  float t1=T*.25*SP+B*.3;p=rotY(t1)*rotX(t1*.7)*p;',
'  float ico=abs(sdIcosa(p,.9+M*.15))-.02-BT*.02;',
'  vec3 q=rotZ(T*.18)*p;',
'  float dod=abs(sdDodeca(q,1.3+H*.12))-.015-BT*.015;',
'  vec3 r=rotY(T*.12)*rotX(-T*.15)*p;',
'  float oct=abs(sdOct(r,1.6+B*.18))-.018-FL*.01;',
'  return min(min(ico,dod),oct);',
'}',
'vec3 calcN(vec3 p){vec2 e=vec2(.002,0);return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),map(p+e.yxy)-map(p-e.yxy),map(p+e.yyx)-map(p-e.yyx)));}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float az=T*.15+MX.x*2.5,el=.3+MX.y*.8;',
'  vec3 ro=vec3(3.5*cos(el)*cos(az),3.5*sin(el),3.5*cos(el)*sin(az));',
'  mat3 ca=camMat(ro,vec3(0.),sin(T*.04)*.02);',
'  vec3 rd=ca*normalize(vec3(sc,1.5));',
'  float td=0.;vec3 col=vec3(.008,.004,.015);',
'  float glow=0.;',
'  for(int i=0;i<76;i++){',
'    vec3 p=ro+rd*td;float d=map(p);',
'    glow+=.015/(d+.08);',
'    if(d<.004){',
'      vec3 n=calcN(p);',
'      col=blinnPhong(n,-rd,normalize(vec3(.4,.6,-.3)),pal(length(p)*.3+T*.07+SC*.2),0.06);',
'      col*=1.+BT*.5+FL*.25;break;',
'    }',
'    if(td>12.)break;td+=d*.75;',
'  }',
'  col+=pal(T*.06+.4)*glow*.032*(1.+BT*.6);',
'  vec2 fUV=feedUV(1.018+B*.015,.003*SP+M*.004,vec2(0.));',
'  col=mix(texture2D(PV,fUV).rgb*.92,col,.32+B*.15);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.87)),1.);',
'}'
].join('\n')});

/* 3. NEURAL SWARM — connected particles forming/dissolving, glow lines */
NX.registerScene({n:'NEURAL SWARM',rx:2,c:'#00e5ff',fs:H+[
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  vec3 col=vec3(.004,.006,.012);',
'  float glow=0.;',
'  float sz=18.;int N=42;',
'  for(int i=0;i<42;i++){',
'    float fi=float(i);',
'    float ph=fi*2.399+T*.08*SP;',
'    float r=(.3+fi/float(N)*.9)*(1.+B*.25+sin(T*.3+fi)*.12);',
'    vec2 pi=vec2(cos(ph)*r,sin(ph*.7+T*.12)*r);',
'    float d=length(sc-pi);',
'    float bright=.0045/(d+.015)*(1.+BT*.6+FL*.3);',
'    vec3 pc=pal(fi/float(N)+T*.04+SC*.15);',
'    col+=pc*bright;glow+=bright;',
'    for(int j=0;j<42;j++){',
'      if(j<=i)continue;',
'      float fj=float(j);',
'      float ph2=fj*2.399+T*.08*SP;',
'      float r2=(.3+fj/float(N)*.9)*(1.+B*.25+sin(T*.3+fj)*.12);',
'      vec2 pj=vec2(cos(ph2)*r2,sin(ph2*.7+T*.12)*r2);',
'      float dl=length(pi-pj);',
'      if(dl>.7)continue;',
'      vec2 ab=pj-pi;float t2=sat(dot(sc-pi,ab)/dot(ab,ab));',
'      float line=length(sc-pi-ab*t2);',
'      float w=.0025/(line+.008)*(1.-dl/.7)*(.5+FL*.6);',
'      col+=pc*w;',
'    }',
'  }',
'  col*=1.+BT*.5;',
'  vec2 fUV=feedUV(1.01+B*.008,.002*SP,vec2(0.));',
'  col=mix(texture2D(PV,fUV).rgb*.91,col,.35+B*.12);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.88)),1.);',
'}'
].join('\n')});

/* 4. DARK MONOLITH — massive obsidian slab, energy climbing up */
NX.registerScene({n:'DARK MONOLITH',c:'#263238',fs:H+[
'float map(vec3 p){',
'  float fl2=p.y+.01;',
'  vec3 q=p-vec3(0.,2.,0.);',
'  float carve=sin(q.y*4.+T*.5)*sin(q.x*6.+T*.3)*.05*M;',
'  float mono=sdBox(q,vec3(.6,2.2,.25))+carve;',
'  float energy=sin(q.y*8.-T*3.+B*4.)*.5+.5;',
'  float crack=sdBox(q-vec3(0.,energy*4.-2.,0.),vec3(.62,.03,.27));',
'  return min(fl2,min(mono,crack));',
'}',
'vec3 calcN(vec3 p){vec2 e=vec2(.002,0);return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),map(p+e.yxy)-map(p-e.yxy),map(p+e.yyx)-map(p-e.yyx)));}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float az=T*.1+MX.x*2.8,el=.35+MX.y*.6;',
'  float dist=5.+sin(T*.12)*.5;',
'  vec3 ro=vec3(dist*cos(el)*cos(az),dist*sin(el)+1.2,dist*cos(el)*sin(az));',
'  mat3 ca=camMat(ro,vec3(0.,1.8,0.),0.);',
'  vec3 rd=ca*normalize(vec3(sc,1.5));',
'  float td=0.;vec3 col=vec3(.005,.004,.006);',
'  float volumetric=0.;',
'  for(int i=0;i<68;i++){',
'    vec3 p=ro+rd*td;float d=map(p);',
'    float climb=sin(p.y*8.-T*3.+B*4.)*.5+.5;',
'    volumetric+=.006*climb/(abs(d)+.05)*(1.+BT*.5);',
'    if(d<.004){',
'      vec3 n=calcN(p);',
'      vec3 ldir=normalize(vec3(.4,.7,-.3));',
'      col=blinnPhong(n,-rd,ldir,pal(p.y*.08+T*.04)*.25,0.02);',
'      float en2=sin(p.y*8.-T*3.+B*4.)*.5+.5;',
'      col+=pal(T*.06+.5)*en2*.4*(1.+BT*.8);',
'      col*=exp(-td*.06);break;',
'    }',
'    if(td>20.)break;td+=d*.7;',
'  }',
'  col+=pal(T*.05+.6)*volumetric*.12;',
'  vec2 fUV=feedUV(1.012+B*.01,.001*SP,vec2(0.));',
'  col=mix(texture2D(PV,fUV).rgb*.93,col,.3+B*.15);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.88)),1.);',
'}'
].join('\n')});

/* 5. LASER CATHEDRAL — volumetric laser beams through haze */
NX.registerScene({n:'LASER CATHEDRAL',rx:2,c:'#ff1744',fs:H+[
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float az=T*.12+MX.x*2.,el=.2+MX.y*.6;',
'  vec3 ro=vec3(3.*cos(el)*cos(az),3.*sin(el)+.8,3.*cos(el)*sin(az));',
'  mat3 ca=camMat(ro,vec3(0.,1.,0.),sin(T*.05)*.01);',
'  vec3 rd=ca*normalize(vec3(sc,1.4));',
'  vec3 col=vec3(.003,.002,.005);',
'  float haze=.0;',
'  int nBeams=5+int(H*3.);',
'  for(int b=0;b<8;b++){',
'    if(b>=nBeams)break;',
'    float fb=float(b);',
'    float phase=fb*PI/float(8)+T*.4*SP+BT*.5;',
'    float sw=sin(phase),cw=cos(phase);',
'    vec3 bDir=normalize(vec3(sw,cw*.3+.7,cw));',
'    vec3 bOrig=vec3(sw*2.,0.,cw*2.);',
'    for(int s=0;s<32;s++){',
'      float ts=float(s)*.25;',
'      vec3 p=bOrig+bDir*ts;',
'      vec3 rp=ro+rd*dot(p-ro,rd);',
'      float d2=length(p-rp);',
'      float beam=.005/(d2*d2+.003)*(1.+BT*.8+FL*.4);',
'      float fogd=exp(-ts*.12-B*.03);',
'      col+=pal(fb/8.+T*.05)*beam*fogd*.08;',
'      haze+=beam*fogd*.005;',
'    }',
'  }',
'  col+=vec3(.06,.02,.04)*haze*(1.+B*.5);',
'  col*=1.+BT*.4;',
'  vec2 fUV=feedUV(1.01+B*.008,.002*SP,vec2(0.));',
'  col=mix(texture2D(PV,fUV).rgb*.92,col,.35+B*.12);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.88)),1.);',
'}'
].join('\n')});

/* 6. AFTERLIFE RINGS — concentric light torus rings in void, breathing */
NX.registerScene({n:'AFTERLIFE RINGS',c:'#b388ff',fs:H+[
'float map(vec3 p){',
'  float d=999.;',
'  for(int i=0;i<7;i++){',
'    float fi=float(i);',
'    float s=.6+fi*.28;',
'    vec3 q=p;',
'    float rA=fi*.9+T*.15*SP;',
'    q=rotX(rA*.7)*rotZ(rA*.5)*q;',
'    float breathing=sin(T*.5+fi*1.2+B*2.)*.08;',
'    float r=sdTorus(q,s+breathing,.035+BT*.02+FL*.01);',
'    d=min(d,r);',
'  }',
'  return d;',
'}',
'vec3 calcN(vec3 p){vec2 e=vec2(.002,0);return normalize(vec3(map(p+e.xyy)-map(p-e.xyy),map(p+e.yxy)-map(p-e.yxy),map(p+e.yyx)-map(p-e.yyx)));}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float az=T*.1+MX.x*2.5,el=.25+MX.y*.7;',
'  vec3 ro=vec3(4.*cos(el)*cos(az),4.*sin(el),4.*cos(el)*sin(az));',
'  mat3 ca=camMat(ro,vec3(0.),sin(T*.035)*.02);',
'  vec3 rd=ca*normalize(vec3(sc,1.5));',
'  float td=0.;vec3 col=vec3(.003,.002,.008);float glow=0.;',
'  for(int i=0;i<72;i++){',
'    vec3 p=ro+rd*td;float d=map(p);',
'    glow+=.02/(d+.06);',
'    if(d<.004){',
'      vec3 n=calcN(p);',
'      col=blinnPhong(n,-rd,normalize(vec3(.3,.6,-.4)),pal(length(p)*.25+T*.06),0.04);',
'      float fres=pow(1.-sat(dot(-rd,n)),2.5);',
'      col+=pal(T*.07+.3)*fres*.35*(1.+FL*.3);',
'      col*=1.+BT*.55;break;',
'    }',
'    if(td>15.)break;td+=d*.7;',
'  }',
'  col+=pal(T*.05+.5)*glow*.018*(1.+BT*.7+FL*.4);',
'  vec2 fUV=feedUV(1.015+B*.012,.003*SP+M*.004,vec2(sin(T*.1)*.001,0.));',
'  col=mix(texture2D(PV,fUV).rgb*.93,col,.3+B*.14);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.87)),1.);',
'}'
].join('\n')});

})();
