'use strict';
(function () {
var H = NX.HEAD;

/* ── Scene 1: HYPERSPACE ─ infinite spiral tunnel corridor ──────────── */
NX.registerScene({n:'HYPERSPACE',rx:2,c:'#00e5ff',fs: H+[
'float tunnelSDF(vec3 p){',
'  float twist=T*SP*.5+B*1.5;p.xy=rot2(twist+p.z*.35)*p.xy;',
'  float r=length(p.xy);',
'  float wall=r-1.3-sin(atan(p.y,p.x)*8.+T*SP*2.5)*(.08+H*.04)-BT*.15;',
'  float zr=opRep1(p.z,2.);',
'  float rib=sdBox(vec3(p.xy-normalize(p.xy)*1.28,zr),vec3(.04,.04,.15));',
'  return min(wall,rib);',
'}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  vec3 ro=vec3(sin(T*SP*.08)*.12+MX.x*.2,cos(T*SP*.06)*.09+MX.y*.15,-2.);',
'  ro.z-=T*SP*4.;',
'  vec3 rd=normalize(vec3(sc*(1.+M*.15),1.2));',
'  float td=0.;',
'  vec3 col=pal(length(sc)*.25+T*.08)*.06;',
'  for(int i=0;i<72;i++){',
'    vec3 pp=ro+rd*td;',
'    pp.z=mod(pp.z,12.)-6.;',
'    float d=tunnelSDF(pp);',
'    if(d<.006){',
'      vec3 e=vec3(.005,0,0);',
'      vec3 n=normalize(vec3(',
'        tunnelSDF(pp+e.xyy)-tunnelSDF(pp-e.xyy),',
'        tunnelSDF(pp+e.yxy)-tunnelSDF(pp-e.yxy),',
'        tunnelSDF(pp+e.yyx)-tunnelSDF(pp-e.yyx)));',
'      float ao=1.-float(i)/72.*.55;',
'      float fres=pow(1.-sat(dot(-rd,n)),2.);',
'      vec3 ldir=normalize(vec3(sin(T)*.5,.3,-1.));',
'      col=blinnPhong(n,-rd,ldir,pal(td*.05+T*.09+B*.35),0.15)*ao;',
'      col+=pal(T*.07+.5)*fres*.4;',
'      col*=(1.+BT*.4+EX*.3);',
'      break;',
'    }',
'    if(td>25.)break;',
'    td+=max(d*.65,.006);',
'  }',
'  vec2 fUV=feedUV(1.022+B*.03,0.004*SP+M*.006,vec2(sin(T*SP*.25)*.002,0.));',
'  vec3 prev=texture2D(PV,fUV).rgb*.93;',
'  col=mix(prev,col,.3+B*.2);',
'  col+=pal(T*.08)*exp(-abs(length(sc)-1.1)*7.)*.35;',
'  gl_FragColor=vec4(sat(col),1.);',
'}'
].join('\n')});

/* ── Scene 2: BLACK HOLE ─ singularity + accretion disk + sphere lattice */
NX.registerScene({n:'BLACK HOLE',c:'#7c4dff',fs: H+[
'float accDisk(vec3 p){',
'  float a=atan(p.z,p.x);',
'  p.y-=sin(a*3.+T*SP*.8)*.03*M;',
'  float r=length(p.xz);',
'  float disk=abs(p.y)-.02-M*.01;',
'  float ring=abs(r-2.5+sin(a*6.+T*SP)*.15)-.4-B*.08;',
'  return max(disk,ring);',
'}',
'float bhScene(vec3 p){',
'  vec3 rp=opRep3(p-vec3(0,0,T*SP*.5),vec3(4.5+B*.3));',
'  float lattice=sdSph(rp,.12+H*.04);',
'  float core=sdSph(p,.45+BT*.1);',
'  vec3 dp=p;dp.xz=rot2(T*SP*.15)*dp.xz;',
'  float disk=accDisk(dp);',
'  return opU(core,opU(disk,lattice));',
'}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float ca=T*SP*.12+MX.x*.5;',
'  vec3 ro=vec3(sin(ca)*5.5,1.8+MX.y*1.5+sin(T*SP*.07)*.6,cos(ca)*5.5);',
'  mat3 cm=camMat(ro,vec3(0),sin(T*SP*.05)*.08);',
'  vec3 rd=cm*normalize(vec3(sc*(1.+M*.1),1.8));',
'  float td=0.;vec3 col=vec3(0.);',
'  for(int i=0;i<80;i++){',
'    vec3 pp=ro+rd*td;',
'    vec3 toC=-pp;float d2c=length(toC);',
'    rd=normalize(rd+toC/(d2c*d2c*d2c+.01)*.008);',
'    float d=bhScene(pp);',
'    if(d<.005){',
'      vec3 e=vec3(.004,0,0);',
'      vec3 n=normalize(vec3(',
'        bhScene(pp+e.xyy)-bhScene(pp-e.xyy),',
'        bhScene(pp+e.yxy)-bhScene(pp-e.yxy),',
'        bhScene(pp+e.yyx)-bhScene(pp-e.yyx)));',
'      float ao=1.-float(i)/80.*.6;',
'      col=blinnPhong(n,-rd,normalize(vec3(.5,.8,-.3)),pal(td*.04+T*.06+length(pp.xz)*.15),.1)*ao;',
'      float fres=pow(1.-sat(dot(-rd,n)),3.);',
'      col+=pal(T*.05+.3)*fres*.5;',
'      col*=(1.+BT*.5+EX*.4);',
'      if(abs(pp.y)<.15){',
'        float r=length(pp.xz);',
'        col+=pal(r*.2+T*.1)*exp(-abs(r-2.5)*3.)*.8*(1.+B*.6);',
'      }',
'      break;',
'    }',
'    if(td>30.)break;',
'    td+=max(d*.7,.005);',
'  }',
'  col+=pal(T*.07+.6)*exp(-length(sc)*2.5)*.3*(1.+BT*.8);',
'  vec2 fUV=feedUV(1.018+B*.02,.003*SP+M*.004,vec2(0.));',
'  vec3 prev=texture2D(PV,fUV).rgb*.91;',
'  col=mix(prev,col,.28+B*.15);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.87)),1.);',
'}'
].join('\n')});

/* ── Scene 3: MANDELBULB ─ power-8 fractal ─────────────────────────── */
NX.registerScene({n:'MANDELBULB',rx:2,c:'#ff9100',fs: H+[
'float mandelbulb(vec3 p){',
'  vec3 z=p;float dr=1.,r=0.;',
'  float pw=8.+sin(T*SP*.15)*1.5+B*.8;',
'  for(int i=0;i<10;i++){',
'    r=length(z);if(r>2.)break;',
'    float th=acos(z.z/r),ph=atan(z.y,z.x);',
'    dr=pow(r,pw-1.)*pw*dr+1.;',
'    float zr=pow(r,pw);th*=pw;ph*=pw;',
'    z=zr*vec3(sin(th)*cos(ph),sin(th)*sin(ph),cos(th))+p;',
'  }',
'  return .5*log(r)*r/dr;',
'}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float ca=T*SP*.08+MX.x*.6;',
'  float ce=.3+sin(T*SP*.06)*.15+MX.y*.3;',
'  vec3 ro=vec3(sin(ca)*cos(ce),sin(ce),cos(ca)*cos(ce))*2.8;',
'  mat3 cm=camMat(ro,vec3(0),0.);',
'  vec3 rd=cm*normalize(vec3(sc,1.6));',
'  float td=0.;float trap=100.;',
'  vec3 col=pal(length(sc)*.2+T*.05)*.04;',
'  for(int i=0;i<84;i++){',
'    vec3 pp=ro+rd*td;',
'    float d=mandelbulb(pp);',
'    trap=min(trap,length(pp.xz));',
'    if(d<.0009){',
'      vec3 e=vec3(.001,0,0);',
'      vec3 n=normalize(vec3(',
'        mandelbulb(pp+e.xyy)-mandelbulb(pp-e.xyy),',
'        mandelbulb(pp+e.yxy)-mandelbulb(pp-e.yxy),',
'        mandelbulb(pp+e.yyx)-mandelbulb(pp-e.yyx)));',
'      float ao=1.-float(i)/84.*.62;',
'      col=blinnPhong(n,-rd,normalize(vec3(.6,.8,-.4)),pal(trap*.35+T*.07+B*.2),.12)*ao;',
'      float fres=pow(1.-sat(dot(-rd,n)),2.2);',
'      col+=pal(T*.06+trap*.4)*fres*.42;',
'      col*=(1.+BT*.52+EX*.38+FL*.22);',
'      break;',
'    }',
'    if(td>9.)break;',
'    td+=d;',
'  }',
'  vec2 fUV=feedUV(1.015+B*.02,.002*SP,vec2(sin(T*SP*.2)*.001,0.));',
'  vec3 prev=texture2D(PV,fUV).rgb*.92;',
'  col=mix(prev,col,.32+B*.18);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.87)),1.);',
'}'
].join('\n')});

/* ── Scene 4: CHROME PLANET ─ planet + orbital filament rings ───────── */
NX.registerScene({n:'CHROME PLANET',c:'#00e5ff',fs: H+[
'float planetSDF(vec3 p){',
'  float nz=vn(p.xz*3.+T*.1)*.12+vn(p.xy*5.)*.04;',
'  float planet=sdSph(p,1.5+nz+B*.04);',
'  vec3 rp=rotX(.35+sin(T*SP*.08)*.1)*p;',
'  float ring1=sdTorus(rp,2.6+sin(T*SP*.2)*.1,.025+H*.008);',
'  rp=rotX(-.6+cos(T*SP*.12)*.08)*rotY(T*SP*.04)*p;',
'  float ring2=sdTorus(rp,3.1,.02+M*.006);',
'  rp=rotX(.9)*rotZ(T*SP*.06)*p;',
'  float ring3=sdTorus(rp,2.9,.018+FL*.005);',
'  return opU(planet,opU(ring1,opU(ring2,ring3)));',
'}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float ca=T*SP*.1+MX.x*.5;',
'  vec3 ro=vec3(sin(ca)*4.5,1.2+MX.y+sin(T*SP*.05)*.5,cos(ca)*4.5);',
'  mat3 cm=camMat(ro,vec3(0),0.);',
'  vec3 rd=cm*normalize(vec3(sc*(1.+M*.08),1.6));',
'  float td=0.;vec3 col=vec3(0.);',
'  for(int i=0;i<70;i++){',
'    vec3 pp=ro+rd*td;',
'    float d=planetSDF(pp);',
'    if(d<.004){',
'      vec3 e=vec3(.003,0,0);',
'      vec3 n=normalize(vec3(',
'        planetSDF(pp+e.xyy)-planetSDF(pp-e.xyy),',
'        planetSDF(pp+e.yxy)-planetSDF(pp-e.yxy),',
'        planetSDF(pp+e.yyx)-planetSDF(pp-e.yyx)));',
'      float ao=1.-float(i)/70.*.5;',
'      vec3 ldir=normalize(vec3(.5,.7,-.5));',
'      vec3 baseCol=pal(dot(n,vec3(0,1,0))*.3+T*.05);',
'      col=blinnPhong(n,-rd,ldir,baseCol,.08)*ao;',
'      vec3 refl=reflect(rd,n);',
'      vec3 envCol=pal(refl.y*.5+refl.x*.3+T*.04);',
'      float fres=pow(1.-sat(dot(-rd,n)),3.);',
'      col=mix(col,envCol,fres*.6+.15);',
'      float spec=pow(sat(dot(n,normalize(ldir-rd))),64.);',
'      col+=vec3(.9,.95,1.)*spec*.7;',
'      col*=(1.+BT*.4+EX*.25);',
'      col+=pal(T*.08)*.15*exp(-abs(length(pp)-1.55)*8.);',
'      break;',
'    }',
'    if(td>20.)break;',
'    td+=max(d*.8,.004);',
'  }',
'  col+=pal(T*.06+.2)*exp(-abs(length(sc)-.4)*4.)*.2*(1.+B*.3);',
'  vec2 fUV=feedUV(1.012+B*.015,.002*SP,vec2(0.));',
'  vec3 prev=texture2D(PV,fUV).rgb*.90;',
'  col=mix(prev,col,.35+B*.15);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.87)),1.);',
'}'
].join('\n')});

/* ── Scene 5: GALAXY CORE ─ spiral arms + volumetric disk ──────────── */
NX.registerScene({n:'GALAXY CORE',c:'#ff6d00',fs: H+[
'float spiralDens(vec3 p){',
'  float r=length(p.xz),a=atan(p.z,p.x);',
'  float arm1=sin(a*2.-r*1.8+T*SP*.3+B*.5)*.5+.5;',
'  float arm2=sin(a*2.-r*1.8+PI+T*SP*.3)*.5+.5;',
'  float arms=pow(max(arm1,arm2),3.5);',
'  float diskH=exp(-p.y*p.y*(5.-B*1.2));',
'  float diskR=1.-smoothstep(0.,4.5+M*.5,r);',
'  float core=exp(-r*1.5-p.y*p.y*3.)*(2.+BT*.8);',
'  float noise=vn(p.xz*2.+T*.15)*.4+.6;',
'  return (arms*diskH*diskR+core)*noise;',
'}',
'void main(){',
'  vec2 sc=(uv-.5)*vec2(R.x/R.y,1.)*2.;',
'  float ca=T*SP*.06+MX.x*.4;',
'  float ce=.5+sin(T*SP*.04)*.2+MX.y*.3;',
'  vec3 ro=vec3(sin(ca)*cos(ce),sin(ce),cos(ca)*cos(ce))*6.;',
'  mat3 cm=camMat(ro,vec3(0),sin(T*SP*.03)*.05);',
'  vec3 rd=cm*normalize(vec3(sc,1.4));',
'  vec3 col=vec3(0.);float alpha=0.,td=0.;',
'  for(int i=0;i<80;i++){',
'    vec3 pp=ro+rd*td;',
'    pp.xz=rot2(T*SP*.02)*pp.xz;',
'    float dens=spiralDens(pp)*.08;',
'    if(dens>.001){',
'      float r=length(pp.xz);',
'      vec3 scol=pal(r*.12+atan(pp.z,pp.x)*.1+T*.05);',
'      scol*=(1.+BT*.5+FL*.3);',
'      col+=scol*dens*(1.-alpha);',
'      alpha+=dens*(1.-alpha);',
'      if(alpha>.97)break;',
'    }',
'    td+=.12+td*.015;',
'    if(td>18.)break;',
'  }',
'  vec2 starUV=sc*8.+vec2(T*SP*.02);',
'  float star=pow(h21(floor(starUV)),28.)*(1.+H*.5);',
'  col+=vec3(star)*(1.-alpha);',
'  col+=pal(T*.07)*exp(-length(sc)*2.)*.4*(1.+BT*.6);',
'  vec2 fUV=feedUV(1.025+B*.025,.005*SP,vec2(sin(T*SP*.15)*.002,0.));',
'  vec3 prev=texture2D(PV,fUV).rgb*.88;',
'  col=mix(prev,col,.25+B*.2);',
'  gl_FragColor=vec4(pow(sat(col),vec3(.87)),1.);',
'}'
].join('\n')});

/* (MANDELBOX culled — too similar to MANDELBULB) */

})();
